apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: k8spsprunasnonroot
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.containers[name:*].securityContext.runAsNonRoot"
  parameters:
    pathTests:
      - subPath: "spec.containers[name:*].securityContext.runAsNonRoot"
        condition: MustNotExist
    assign:
      value: true
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: k8spsprunasnonroot-init
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.initContainers[name:*].securityContext.runAsNonRoot"
  parameters:
    pathTests:
      - subPath: "spec.initContainers[name:*].securityContext.runAsNonRoot"
        condition: MustNotExist
    assign:
      value: true