{{- if and .Values.global.dev .Values.global.localDev }}
{{- if .Values.rustfs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-secret
  namespace: {{ .Values.rustfs.namespace }}
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  access_key: "rustfsadmin"
  secret_key: "rustfsadmin"

---

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
stringData:
  config: |
    [default]
    endpoint_url=http://host:port
  credentials: |
    [default]
    aws_access_key_id=rustfsadmin
    aws_secret_access_key=rustfsadmin

---
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: "{{ .Values.prometheus.grafana.adminSecretName }}"
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: "grafanaAdm1n!"
  admin-user: "admin"

{{- end }}