apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: "{{ .Values.prometheus.namespace }}"
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  admin-password: "{{ .Values.prometheus.grafana.adminPassword }}"
  admin-user: "admin"
