{{- if .Values.gatekeeper.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-gatekeeper
  namespace: {{ .Values.global.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
spec:
  project: {{ .Values.global.argoProject }}
  destination:
    namespace: {{ .Values.gatekeeper.namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        "admission.gatekeeper.sh/ignore": "pleaseignore"
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      refresh: true
  ignoreDifferences:
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
      jsonPointers:
        - /spec/preserveUnknownFields
  source:
    repoURL: {{ .Values.gatekeeper.repoURL }}
    chart: {{ .Values.gatekeeper.chart }}
    targetRevision: {{ .Values.gatekeeper.chartVersion }}
    helm:
      valuesObject:
        auditMatchKindOnly: true

        auditInterval: 240

        validatingWebhookExemptNamespacesLabels:
          "admission.gatekeeper.sh/ignore":
            - "pleaseignore"
          "kubernetes.io/metadata.name":
            - "kube-system"
            - "kube-node-lease"
            - "kube-public"
            - "local-path-storage"
            - "{{ .Values.gatekeeper.namespace }}"
            - "{{ .Values.falco.namespace }}"
            - "{{ .Values.prometheus.namespace }}"
            - "{{ .Values.certManager.namespace }}"
            # ingress controller
            - "ingress-nginx"
            - "argocd"
            {{- with .Values.gatekeeper.extraExempt.namespaces }}
            - "{{ . }}"
            {{- end }}

        mutatingWebhookExemptNamespacesLabels:
          "admission.gatekeeper.sh/ignore":
            - "pleaseignore"
          "kubernetes.io/metadata.name":
            - "kube-system"
            - "kube-node-lease"
            - "kube-public"
            - "local-path-storage"
            - "{{ .Values.gatekeeper.namespace }}"
            - "{{ .Values.falco.namespace }}"
            - "{{ .Values.prometheus.namespace }}"
            - "{{ .Values.certManager.namespace }}"
            # ingress controller
            - "ingress-nginx"
            - "argocd"
            {{- with .Values.gatekeeper.extraExempt.namespaces }}
            - "{{ . }}"
            {{- end }}

        controllerManager:
          exemptNamespaces:
            - "kube-system"
            - "kube-node-lease"
            - "kube-public"
            - "local-path-storage"
            - "{{ .Values.gatekeeper.namespace }}"
            - "{{ .Values.falco.namespace }}"
            - "{{ .Values.prometheus.namespace }}"
            - "{{ .Values.certManager.namespace }}"
            # ingress controller
            - "ingress-nginx"
            - "argocd"
            {{- with .Values.gatekeeper.extraExempt.namespaces }}
            - "{{ . }}"
            {{- end }}
            
{{- end }}