{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tesk
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector:
    matchExpressions:
      - key: job-name
        operator: Exists
  egress:
    # temp allow all egress for debugging
    - {} 
    - ports:
        - protocol: TCP
          port: 8080
      to:
        - podSelector:
            matchLabels:
              app: tesk-api
    - ports:
        - protocol: TCP
          port: 1
          endPort: 32768
      to:
        # this is the ip of the egress minio
        - ipBlock:
            cidr: {{ .Values.networkPolicy.egressMinioIP }}/32
        # this is the kube api which i don't like that it needs access to
        - ipBlock:
            cidr: {{ .Values.networkPolicy.kubeApiIP }}/32
        - ipBlock:
            cidr: {{ .Values.networkPolicy.kubeApiSvcIP }}/32
        {{- range .Values.networkPolicy.extraEgressIPs }}
        - ipBlock:
            cidr: {{ . }}/32
        {{- end }}

    # cluster DNS or something?
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  policyTypes:
    - Egress

{{- end }}