{{- if .Values.networkPolicy.enabled }}

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tesk
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  endpointSelector:
    matchExpressions:
      - key: job-name
        operator: Exists

  egress:
    # 1) tesk-api on 8080 (same-namespace pod selector)
    - toEndpoints:
        - matchLabels:
            app: tesk-api
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP

    # 2) MinIO egress IP (you were allowing TCP 1-32768; keep that intent)
    - toCIDR:
        - {{ .Values.networkPolicy.egressMinioIP }}/32
      toPorts:
        - ports:
          - port: "1"
            endPort: 32768
            protocol: TCP

    # 3) Kubernetes API (
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP


    # 4) Extra egress IPs on all ports so we don't have to derive that
    - toCIDRSet:
        {{- range .Values.networkPolicy.extraEgressIPs }}
        - cidr: {{ . }}/32
        {{- end }}
      toPorts:
        - ports:
            - port: "1"
              endPort: 32768
              protocol: TCP

    # 6) DNS to kube-dns in kube-system
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
            - matchPattern: "*"

{{- end }}