{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tesk
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      job-name: task-*
  egress:
    - ports:
        - protocol: TCP
          port: 8080
      to:
        - podSelector:
            matchLabels:
              app: tesk-api
    - ports:
        - protocol: TCP
          port: 1
          endPort: 32768
      to:
        {{- if .Values.outputLocationConfig.external }}
        # this is the ip of the egress minio
        - ipBlock:
            cidr: {{ .Values.outputLocationConfig.ip }}/32
        {{- else }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.rustfs.namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: rustfs
        {{- end }}
    # cluster DNS or something?
    - ports:
        - protocol: UDP
          port: 53
      to:
        - namespaceSelector:
            matchLabels:
              networking/namespace: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  policyTypes:
    - Egress

{{- end }}